### ISSUE TITLE
Generate the static profile

### ISSUE THREAD

**Issue by bmaggi** [patnan/papyrus_anatomy#5]
Steps: 
- create the genmodel file
  - generate the code in src-gen
  - check that the profile is correctly defined in a URI

**Comment by patnan** [comment]
I've never generated a static profile before. How do I create the genmodel? Do I generate it using the wizard and select UML model?

Also when I've generated the code, should I change any extensions in plugin.xml? I.e. do I gregister the profile differently when it is stattic?

**Comment by bmaggi** [comment]
You have to install emf sdk and uml2 sdk.
Use the wizard to create a new genmodel file and select the profile as model entry.

Emf generation works only with ecore model, so the tooling will generate an .ecore file (you will have to reload this each time you modify your profile)

Note that the Papyrus perspective will prevent you to open the file. Open it in the Java perspective.

Once opened:
- change the src target directory from src to src-gen
- right click on the root to generate the "model" 

-> this will also modify your plugin.xml

**Comment by patnan** [comment]
Just trying to get this to work.

>  Use the wizard to create a new genmodel file and select the profile as model entry.

When you say select the profile as model entry, do you mean to select 'UML Model' in the EMF Generator Models 'Select Model Importer' wizard page and then select the profile file? 

If so, when I do that I get a lot of warnings
